version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    command: ["redis-server", "--requirepass", "my_secure_password"]
    environment:
      - REDIS_PASSWORD=my_secure_password
    network_mode: host
    ports:
      - "6379:6379"
    restart: always

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: p4slice-api
    network_mode: host
    ports:
      - "8080:8080"
    depends_on:
      - redis
    restart: always
