version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    network_mode: host
    ports:
      - "6379:6379"
    restart: always

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    network_mode: host
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=redis:6379
      - SERVER_URL=127.0.0.1
      - SERVER_PORT=8080
      - GRPC_URLS=127.0.0.1:50052
    depends_on:
      - redis
    restart: always
