services:
  redis:
    image: redis:latest
    container_name: redis
    command: ["redis-server", "--requirepass", "dff3b2d5437e66dc9d53eb10caa145f823e7422f6c0074559858cb191be87e19"]
    ports:
      - 6379:6379
    restart: always

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: p4slice-api
    ports:
      - 8080:8080
    depends_on:
      - redis
    configs:
      - api_config
    environment:
      CONFIG_PATH: "/api_config"
    restart: on-failure:3

configs:
  api_config:
    file: ./config.json
